version: '3'
services:
  nginx:
    build: 
      context: ./dockerfiles/nginx
      args:
        WEB_USER_GID: 1000
        WEB_USER_UID: 1000
    restart: always
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/:/var/www/html:ro
    ports:
      - 80:80
      - 443:443
      - 4443:4443
    depends_on:
      - pythonstuff
  pythonstuff:
    build: 
      context: ./server/
    restart: always

